name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.7
    - run: dotnet add package Newtonsoft.Json
    - run: dotnet add package Microsoft.Web.WebView2
